version: '3'
services:
  hair-app:
    build:
      context: ./config
      dockerfile: php.dockerfile
      args:
        - USER_NAME=$USER
        - USER_ID=$USER_ID
        - DOCKERFILE=local
    working_dir: /var/www
    image: 'hair-app'
    container_name: 'hair-app'
    ports:
      - 8005:8000
    volumes:
      - ./source/hair_app:/var/www
      - vendor:/var/www/vendor
      - node_modules:/var/www/node_modules
    networks:
      - app-network

  db:
    image: mysql:8.2
    container_name: hair-app-db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    working_dir: /var/lib/mysql
    volumes:
      - datadb:/var/lib/mysql
    networks:
      - app-network

  pma:
    image: phpmyadmin/phpmyadmin:latest
    container_name: hair-app-pma
    environment:
      - MAX_EXECUTION_TIME=600
      - UPLOAD_LIMIT=800M
      - PMA_HOST=hair-app-db
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
      - PMA_PASSWORD= ${DB_PASSWORD}
      - PMA_CONTROLPASS= ${DB_PASSWORD}
    depends_on:
      - db
    ports:
      - 8008:80
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: hair-app-nginx
    ports:
      - 8000:80
    volumes:
      - ./source/hair_app:/var/www
      - ./config/nginx:/etc/nginx/conf.d/
    networks:
      - app-network

  websocket-server:
    image: quay.io/soketi/soketi:latest-16-alpine
    environment:
      SOKETI_DEBUG: '1'
      SOKETI_METRICS_SERVER_PORT: '9601'
    container_name: websocket-server
    ports:
      - 6001:6001
      - 9601:9601
    networks:
      - app-network

  hair_service:
    container_name: hair-service
    build:
      context: ./config/python
      dockerfile: python.dockerfile
      args:
        - USER_NAME=$USER
        - USER_ID=$USER_ID
        - DOCKERFILE=local
    ports:
      - 8003:80
    volumes:
      - ./source/hair_service:/usr/src/app
    networks:
      - app-network

  # node:
  #   #https://vitejs.dev/config/server-options.html 
  #   build: 
  #     context: ./config
  #     dockerfile: node.dockerfile
  #   container_name: "hair-app-node"
  #   environment:
  #     - NODE_ENV="development"
  #   volumes:
  #     - ./source/hair_app:/var/www
  #     - vendor:/var/www/vendor
  #     - node_modules:/var/www/node_modules
  #   command:
  #     - sh
  #     - -c
  #     - |
  #       npm install --quit
  #       #npm update --quit
  #       npm run dev
  #   ports:
  #     - 5173:5173
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
volumes:
  datadb:
  vendor:
  node_modules:
