# Generated by Django 5.0 on 2023-12-21 02:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ZonaTransporte', '0001_initial'),
        ('localidades', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del cliente', max_length=100)),
                ('direccion', models.CharField(help_text='Dirección', max_length=100)),
                ('coord_x', models.FloatField(help_text='Coordenadas x')),
                ('coord_y', models.FloatField(help_text='Coordenadas y')),
                ('costo_almacenamiento', models.FloatField(help_text='Costo de almacenamiento')),
                ('nivel_almacenamiento', models.IntegerField(help_text='Nivel actual')),
                ('nivel_maximo', models.IntegerField(help_text='Nivel máximo')),
                ('nivel_minimo', models.IntegerField(help_text='Nivel de mínimo')),
                ('nivel_demanda', models.IntegerField(help_text='Nivel de demanda')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localidades.localidad')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZonaTransporte.zona')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del cliente', max_length=100)),
                ('direccion', models.CharField(help_text='Dirección', max_length=100)),
                ('coord_x', models.FloatField(help_text='Coordenadas x')),
                ('coord_y', models.FloatField(help_text='Coordenadas y')),
                ('costo_almacenamiento', models.FloatField(help_text='Costo de almacenamiento')),
                ('nivel_almacenamiento', models.IntegerField(help_text='Nivel actual')),
                ('nivel_maximo', models.IntegerField(help_text='Nivel máximo')),
                ('nivel_minimo', models.IntegerField(help_text='Nivel de mínimo')),
                ('nivel_produccion', models.IntegerField(help_text='Nivel de producción')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localidades.localidad')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZonaTransporte.zona')),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
