# Generated by Django 5.0 on 2023-12-27 03:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre de la zona', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(help_text='Patente', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('marca', models.CharField(help_text='Nombre de la marca', max_length=50)),
                ('nombre_modelo', models.CharField(help_text='Nombre del modelo', max_length=50)),
                ('anio', models.IntegerField(help_text='Año', validators=[django.core.validators.MinValueValidator(2010), django.core.validators.MaxValueValidator(2024)])),
                ('color', models.CharField(help_text='Color', max_length=50)),
                ('capacidad', models.IntegerField(help_text='Capacidad del vehículo')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZonaTransporte.zona')),
            ],
        ),
    ]
