# Generated by Django 5.0 on 2023-12-12 01:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(help_text='Patente', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('marca', models.CharField(help_text='Nombre de la marca', max_length=50)),
                ('modelo', models.CharField(help_text='Nombre del modelo', max_length=50)),
                ('color', models.CharField(help_text='Color', max_length=50)),
                ('capacidad', models.IntegerField(help_text='Capacidad del vehículo')),
                ('asignado', models.BooleanField(help_text='¿Asignado a una Zona?')),
                ('disponible', models.BooleanField(help_text='¿Disponible?')),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre de la zona', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehiculoXZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateField(help_text='Fecha de vinculación')),
                ('fecha_baja', models.DateField(help_text='Fecha de desvinculación', null=True)),
                ('vehiculo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZonaTransporte.vehiculo')),
                ('zona_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZonaTransporte.zona')),
            ],
        ),
    ]
