# Generated by Django 5.0 on 2024-01-09 02:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZonaTransporte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='anio',
            field=models.IntegerField(help_text='Año', validators=[django.core.validators.MinValueValidator(2010), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
