# Generated by Django 5.0 on 2023-12-12 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZonaTransporte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='asignado',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='disponible',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='zona',
            field=models.ForeignKey(help_text='Asignado a Zona', null=True, on_delete=django.db.models.deletion.CASCADE, to='ZonaTransporte.zona'),
        ),
    ]
