# Generated by Django 5.0 on 2023-12-12 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZonaTransporte', '0003_alter_vehiculo_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='zona',
            field=models.ForeignKey(help_text='Asignado a Zona', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ZonaTransporte.zona'),
        ),
    ]
