# Generated by Django 5.0 on 2023-12-13 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZonaTransporte', '0005_alter_vehiculo_zona'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehiculo',
            unique_together={('zona',)},
        ),
    ]
