# Generated by Django 5.0 on 2024-01-09 02:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ZonaTransporte', '0002_alter_vehiculo_anio'),
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solucion',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('politica_reabastecimiento', models.CharField(help_text='Política de reabastecimiento', max_length=100)),
                ('estado', models.IntegerField(help_text='Estado de la solución')),
                ('costo', models.FloatField(help_text='Costo calculado de la solución')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZonaTransporte.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(help_text='Fecha de entrega')),
                ('costo', models.FloatField(help_text='Costo de la ruta calculada')),
                ('solucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soluciones.solucion')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orden', models.IntegerField(help_text='Orden de entrega')),
                ('cantidad', models.IntegerField(help_text='Cantidad entregada')),
                ('realizada', models.DateTimeField(help_text='Fecha y hora de visita')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.cliente')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soluciones.ruta')),
            ],
        ),
    ]
