# Generated by Django 5.0 on 2024-01-12 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soluciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solucion',
            options={'verbose_name_plural': 'Soluciones'},
        ),
    ]
