# Generated by Django 5.0 on 2024-01-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soluciones', '0002_alter_solucion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='realizada',
            field=models.DateTimeField(help_text='Fecha y hora de visita', null=True),
        ),
    ]
